import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";  // Ensure this path is correct
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Video Background */}
        <div className="video-background">
          <video autoPlay muted loop>
            <source src="/sparks.mp4" type="video/mp4" />
            Your browser does not support the video tag.
          </video>
        </div>

        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
